# Generated by Django 5.0.4 on 2024-04-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='ia_staff',
            new_name='is_staff',
        ),
    ]
